export const MENUS = [
  { name: "Search", icon: "􀊫", path: "" },
  { name: "Tender Task", icon: "􀥜", path: "" },
  { name: "Analytics", icon: "􀑁", path: "" },
  { name: "Contact us", icon: "􀌾", path: "" },
];

export const TODOLIST = [
  {
    status: "In Progress",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Not Started",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "In Progress",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "In Progress",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "In Progress",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "In Progress",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Not Started",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Not Started",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Completed",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "High",
    comments: 12,
    attachments: 3,
  },
  {
    status: "Not Started",
    title: "Construction Tender 1",
    description: "Description goes in here about the tender",
    assignee: "User",
    date: "22 Dec 24",
    priority: "Low",
    comments: 12,
    attachments: 3,
  },
];
